### ISSUE TITLE
Support multiple init files

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/cosmwasm-js#149]
If I have some generic setup code (helpers) and some contract-specific code (see #148) it would be nice to import both of them without merging the source files. This could be done if we support multiple instances of `--init` in `packages/cli/src/cli.ts`

```ts
export function main(originalArgs: readonly string[]): void {
  const parser = new ArgumentParser({ description: "The CosmWasm REPL" });
  parser.addArgument("--version", {
    action: "storeTrue",
    help: "Print version and exit",
  });
  parser.addArgument("--init", {
    metavar: "FILEPATH",
    help: "Read initial TypeScript code from file",
  });
  // ...
    if (args.init) {
    init += fs.readFileSync(args.init, "utf8") + "\n";
  }
```

**Comment by ethanfrey** [comment]
@webmaster128 can you take a look at this? Since you wrote these cli arg parser.

I will be updating some examples (#147)

**Comment by webmaster128** [comment]
Sure, sounds like a simple change

**Comment by ethanfrey** [comment]
Thanks
